[project]
name = "alles-gesagt-scraper"
version = "0.1.0"
description = "Scrape all \"ZEIT Alles gesagt?\" podcast episodes. "
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "types-beautifulsoup4>=4.12.0.20250516",
    "types-requests>=2.32.4.20260107",
]

[project.scripts]
alles-gesagt-scraper = "alles_gesagt:main"

[tool.setuptools.packages.find]
include = ["alles_gesagt*"]